---
# tasks file for base-config
- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  template:
    src: repos_template.j2
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

- name: check current repositories in yum.repos.d
  command: "ls -1 /etc/yum.repos.d/* | while read i ;do echo $i ; cat $i ;done"
  register: r_repos

- debug:
    var: r_repos.stdout

- name: Clearing yum cache
  command: yum clean all

#- name: setup hostname
#  hostname:
#    name: "{{ inventory_hostname }}"
 
- name: install base tools and packages
  yum:
    name: "{{ item }}" 
    state: latest
  with_items:
    - httpie
    - python-pip
